name: Aldryn Grid (Foundation)
package-name: aldryn-grid-foundation
url: https://github.com/aldryn/aldryn-grid-foundation
author:
  name: Divio AG
  url: https://www.divio.ch
installed-apps:
  - aldryn_grid_foundation
version: 0.0.5
description: A Multi Column Plugin for Aldryn based on the Foundation grid system.
license:
  name: BSD
  text: !literal-include LICENSE.txt
